#!/bin/bash
sudo apt update
sudo apt install software-properties-common -y
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt update
sudo apt install ansible -y
sudo apt install nginx -y
sudo apt install python3-apt -y
sudo apt install stress -y 
sudo apt install git -y  
sudo git clone https://github.com/mohit-decoder/scorekeeper.git


#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook -i playbook.yaml

